server:
  port: 8770
  
  
spring:
  application:
    name: StudentResult
#  datasource:
#    username: Akash
##    password: postgres
#    url: jdbc:postgresql://localhost:5432/postgres 
#    password: Akash2141
##    url: jdbc:postgresql://postgres.cyp1vjctaigy.ap-south-1.rds.amazonaws.com:5432/postgres
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
    